name: liv_farm
description: livFarm application

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.2.3+34
# 버전 수정

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #Icons
  cupertino_icons: ^1.0.4
  font_awesome_flutter: ^9.2.0
  #Payment
  iamport_flutter: ^0.10.0
  #State Management
  stacked: ^2.2.7+1
  stacked_services: ^0.8.16
  #Http call
  http: ^0.13.4
  #Manage Token
  flutter_secure_storage: ^5.0.2
  # Auth Package
  kakao_flutter_sdk: ^0.9.0
  sign_in_with_apple: ^3.3.0
  google_sign_in: ^5.2.1
  #In async call
  loading_overlay: ^0.3.0
  #animations
  animations: ^2.0.2
  #caching image
  cached_network_image: ^3.2.0
  #indicator
  bubble_tab_indicator: ^0.1.6
  #Toast Message
  fluttertoast: ^8.0.8
  #URL lancher
  url_launcher: ^6.0.17
  #Version management
  store_redirect: ^2.0.0
  package_info: ^2.0.2
  #Badge
  badges: ^2.0.2
  #Star rating
  flutter_rating_bar: ^4.0.0
  webview_flutter: ^2.0.4
  #Add Firebase Analytics
  firebase_analytics: ^9.0.4
  firebase_core: ^1.10.6
  location: ^4.3.0
  observable_ish: ^3.0.1
  firebase_dynamic_links: ^4.0.3
  qr_code_scanner: ^0.6.1
  permission_handler: ^8.3.0
  flutter_html: ^2.2.1
  flutter_inappwebview: ^5.3.2
  draggable_home: ^1.0.2
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  stacked_generator:
  flutter_lints: ^1.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/
    - assets/files/
    - assets/daum_search.html
  fonts:
    - family: "Spoqa Han Sans"
      fonts:
        - asset: assets/fonts/Spoqa Han Sans Regular.ttf
    - family: MyIcons
      fonts:
        - asset: assets/fonts/MyIcons.ttf
