name: liv_farm
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  provider: ^4.3.2+2
  shared_preferences: ^0.5.12
  json_serializable: ^3.5.0
  platform: ^2.2.1
  package_info: ^0.4.3
  http: ^0.12.2
  modal_progress_hud: ^0.1.3
  kakao_flutter_sdk: ^0.5.2
  dio: ^3.0.10
  kopo: "^0.1.3"
  webview_flutter: ^1.0.7
  geolocator: ^6.1.8
  fluttertoast: ^7.1.5
  logger: ^0.9.4
  font_awesome_flutter: ^8.10.0
  firebase_core: ^0.5.3
  firebase_auth: ^0.18.4+1
  firebase_analytics: ^5.0.2
  google_sign_in: ^4.5.6
  flutter_facebook_login: ^3.0.0
  apple_sign_in: ^0.1.0
  modal_bottom_sheet: ^1.0.0+1
  iamport_flutter: ^0.9.13
  badges: ^1.1.6
  flutter_rating_bar: ^3.2.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: 'Spoqa Han Sans'
      fonts:
        - asset: assets/fonts/Spoqa Han Sans Regular.ttf
        - asset: assets/fonts/Spoqa Han Sans Bold.ttf
          weight: 700
        - asset: assets/fonts/Spoqa Han Sans Light.ttf
          weight: 300
        - asset: assets/fonts/Spoqa Han Sans Thin.ttf
          weight: 200
    - family: 'UiIcons'
      fonts:
        - asset: assets/fonts/ui_icons.ttf
